# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Littleboy Application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Fazer checkout do código
    - name: Checkout code
      uses: actions/checkout@v4

    # Passo 2: Configurar Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Passo 3: Instalar as dependências do projeto
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Passo 4: Linting com flake8 (verificar erros de código)
    - name: Lint with flake8
      run: |
        # Interromper se houver erros de sintaxe críticos
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Checar a complexidade e tamanho das linhas, tratando erros como avisos
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Passo 5: Testar com pytest (executar testes automatizados)
    - name: Test with pytest
      run: |
        pytest
